#!/usr/bin/env bash

fullsize="$((2560 + 2560 + 1920))x1440"

s1="DP-2-3"
m1="2560x1440"
f1="59.95"
o1="0x0"

s2="HDMI-1"
m2="2560x1440"
f2="59.95"
o2="2560x0"

s3="eDP-1"
m3="1920x1080"
f3="60.03"
o3="5120x0"

# Adjust screen resolutions
xrandr --fb "$fullsize" \
    --output "$s1" --mode "$m1" --pos "$o1" --rate "$f1" \
    --output "$s2" --mode "$m2" --pos "$o2" --rate "$f2" \
    --output "$s3" --mode "$m3" --pos "$o3" --rate "$f3"

# Set wallpaper
feh --bg-scale ~/.i3/wallhaven-0plj7p.jpg

