#!/usr/bin/env bash

fullsize="1920x1080"

s1="eDP-1"
m1="1920x1080"
f1="60.03"
o1="0x0"

# Adjust screen resolutions
xrandr --fb "$fullsize" --output "$s1" --mode "$m1" --pos "$o1" --rate "$f1"

# Set wallpaper
feh --bg-scale ~/.i3/wallhaven-0plj7p.jpg

